/* CCNA1 Question Difficulty Ratings
   Values: "easy" | "medium" | "hard"
   Edit directly here, or use the Export button in the app and commit the downloaded file.
   Commit this file to GitHub to sync your ratings across machines. */
window.DIFFICULTY_DATA = {
  "5": "easy",
  "7": "medium",
  "9": "medium",
  "11": "medium",
  "16": "easy",
  "19": "easy",
  "20": "medium",
  "26": "medium",
  "27": "easy",
  "33": "easy",
  "34": "hard",
  "38": "hard",
  "39": "hard",
  "40": "medium",
  "41": "medium",
  "44": "easy",
  "45": "medium",
  "46": "easy",
  "49": "medium",
  "50": "easy",
  "56": "medium",
  "57": "medium",
  "59": "easy",
  "62": "hard",
  "63": "medium",
  "66": "easy",
  "69": "medium",
  "75": "medium",
  "76": "medium",
  "77": "hard",
  "78": "hard",
  "79": "medium",
  "81": "medium",
  "82": "easy",
  "84": "medium",
  "86": "hard",
  "90": "medium",
  "91": "hard",
  "93": "hard",
  "95": "hard",
  "97": "hard",
  "98": "medium",
  "101": "medium",
  "105": "medium",
  "106": "easy",
  "111": "medium",
  "112": "medium",
  "113": "medium",
  "114": "medium"
};
